import { test, expect } from 'claude-code/testing'
import { HOST } from '../../hooks/core/host.ts'
import { NOT_STARTED_GENERIC, commandFailed, headlessText, notPerson, notStarted, notice, questionText, resumePrompt, simulateReply, statusReport, stopReply, unknownVerb } from '../../hooks/core/text.ts'
import type { Facts, Named, StatusInput } from '../../hooks/core/text.ts'

// The host words (Codex design 2.1, 8.1). Under the Claude words, every text that takes a host word renders
// the literal of 8a342db, byte for byte. The literals below come from the text.ts of 8a342db.

const TZ = 'UTC'
const T0 = Date.parse('2026-09-24T12:00:00Z')
const R = Date.parse('2026-09-24T15:00:00.000Z') // 3 h after T0
const W = Date.parse('2026-09-27T15:00:00.000Z') // the weekly reset
const MIN = 60_000

const F: Facts = { used: 92, left: 8, resetsAtMs: R, reserve: 10, timeZone: TZ }
const FW: Facts = { used: 93, left: 7, resetsAtMs: W, reserve: 10, timeZone: TZ, kind: 'seven_day', now: T0 }
const LEAD: Facts = { ...F, span: 20 * MIN } // a skip owner: its question names {lead}
const FIVE: Named[] = [{ kind: 'five_hour', test: false }]

const status = (over: Partial<StatusInput> = {}): StatusInput => ({
  phase: 'armed',
  mode: 'hold',
  reserve: 10,
  reserveFrom: 'option',
  pausePrompt: null,
  attended: true,
  headless: 'off',
  headlessFrom: 'option',
  childPolicy: 'stop',
  enabled: true,
  enabledFrom: 'scope',
  scope: 'all',
  basis: { kind: 'live', pct: 50, resetsAtMs: R },
  facts: { used: 50, left: 50, resetsAtMs: R, reserve: 10, timeZone: TZ },
  now: T0,
  toldCount: 0,
  warnings: [],
  timeZone: TZ,
  ...over,
})

// Every optional row, each from its option: the weekly window, the reset row, both spans and both floors.
const full = (over: Partial<StatusInput> = {}): StatusInput =>
  status({
    weekly: { reserve: 10, from: 'option', basis: { kind: 'live', pct: 61, resetsAtMs: W } },
    autoResume: { on: true, from: 'option' },
    spans: { lastMinutes: 20, lastMinutesFrom: 'option', weeklyLastHours: 8, weeklyLastHoursFrom: 'option' },
    floors: { resumeFloor: 5, resumeFloorFrom: 'option', weeklyResumeFloor: 5, weeklyResumeFloorFrom: 'option' },
    ...over,
  })

test('HOST has the Claude Code words', () => {
  expect(HOST).toEqual({
    name: 'Claude Code',
    command: '/spare10',
    anytime: '/spare10',
    config: '/config',
    child: 'claude -p',
    resume: 'claude --resume',
    keepOpen: 'set its Open reserve option to 0 in /config',
    backIt: 'gives it back to you',
    backPrompt: 'gives your prompt back',
    blind: 'Claude Code reports no 5-hour quota.',
    leadSimulate: '/spare10 simulate',
    leadFailed: '/spare10',
    stoppedAgent: 'A subagent whose result says "spare10: work stopped" or "spare10: the user stopped work" did not finish.',
    dialog: 'dialog',
    optIn: 'Start with SPARE10=on to guard a run.',
    unreadSource: 'the env',
  })
  expect(HOST.child.length).toBeLessThanOrEqual(15)
})

const GOLDEN: ReadonlyArray<readonly [string, () => string, string]> = [
  ['NOT_STARTED_GENERIC', () => NOT_STARTED_GENERIC, 'spare10: not started. spare10 could not ask you. Send the prompt again, or run /spare10 resume.'],
  ['notStarted, one window', () => notStarted(F), 'spare10: not started. This session is inside your 10% reserve until 15:00. Send the prompt again to be asked again, or run /spare10 resume.'],
  ['notStarted, both windows', () => notStarted([F, FW]), 'spare10: not started. This session is inside your 10% reserve and your 10% weekly reserve until they reset (15:00 and Sun 15:00). Send the prompt again to be asked again, or run /spare10 resume.'],
  ['headlessText', () => headlessText(F, 'S1'), 'spare10 stopped this unattended run at the quota reserve (into your 10% reserve · 8% of quota left · resets 15:00). No further model requests were sent. To pick it up later: claude --resume S1'],
  ['questionText, prompt opener, tell mode, auto', () => questionText(F, 'prompt', 'tell', true), 'Your 10% reserve is reached: 92% used · 8% left · resets 15:00. spare10 holds your prompt. Continue on the reserve until 15:00? If you do not answer, your prompt goes in after 15:00, unless a reserve is still reached. Stop here gives it back to you.'],
  ['questionText, prompt opener, hold mode, auto', () => questionText(F, 'prompt', 'hold', true), 'Your 10% reserve is reached: 92% used · 8% left · resets 15:00. spare10 holds your prompt and any other work. Continue on the reserve until 15:00? If you do not answer, all of it continues after 15:00, unless a reserve is still reached. Stop here gives your prompt back and pauses other work until 15:00.'],
  ['questionText, prompt opener, tell mode, auto, a skip owner', () => questionText(LEAD, 'prompt', 'tell', true), 'Your 10% reserve is reached: 92% used · 8% left · resets 15:00. spare10 holds your prompt. Continue on the reserve until 15:00? If you do not answer, your prompt goes in at 14:40, 20 min before the reset, unless a reserve is still reached. Stop here gives it back to you.'],
  ['questionText, prompt opener, hold mode, auto, a skip owner', () => questionText(LEAD, 'prompt', 'hold', true), 'Your 10% reserve is reached: 92% used · 8% left · resets 15:00. spare10 holds your prompt and any other work. Continue on the reserve until 15:00? If you do not answer, all of it continues at 14:40, 20 min before the reset, unless a reserve is still reached. Stop here gives your prompt back and pauses other work until 14:40.'],
  ['questionText, loop opener, hold mode, auto', () => questionText(F, 'loop', 'hold', true), 'Your 10% reserve is reached: 92% used · 8% left · resets 15:00. All work is on hold. Continue on the reserve until 15:00? If you choose Stop here or do not answer, the work waits until 15:00. Then spare10 continues it, unless a reserve is still reached.'],
  ['resumePrompt at the reset (RESUME_TAIL)', () => resumePrompt(FIVE), 'The 5-hour window reset, so the stop at the quota reserve is over. spare10 is set to continue the work at the reset, so do not wait for the user. Continue the task from the point where it stopped. A subagent whose result says "spare10: work stopped" or "spare10: the user stopped work" did not finish. Run it again if you still need its result.'],
  ['resumePrompt when the reserve opens (RESUME_TAIL)', () => resumePrompt([], [LEAD]), 'The 5-hour window resets at 15:00. Your 10% reserve is open until then, so the stop at the quota reserve is over. spare10 is set to continue the work when the reserve opens, so do not wait for the user. Continue the task from the point where it stopped. A subagent whose result says "spare10: work stopped" or "spare10: the user stopped work" did not finish. Run it again if you still need its result.'],
  ['notice.stopped', () => notice.stopped(F), 'stopped at your 10% reserve. Type a prompt to be asked again, or run /spare10 resume.'],
  ['notice.stopped until a time', () => notice.stopped(F, { at: '15:05', work: false }), 'stopped at your 10% reserve until 15:05. Type a prompt to be asked again, or run /spare10 resume.'],
  ['notice.stopped until a time, with work', () => notice.stopped(F, { at: '15:05', work: true }), 'stopped at your 10% reserve until 15:05. Then spare10 continues the work, unless a reserve is still reached. Type a prompt to be asked again, or run /spare10 resume.'],
  ['notice.holdLimit', () => notice.holdLimit(F), 'the hold reached its time limit. The work is stopped at your 10% reserve. Type a prompt to be asked again, or run /spare10 resume.'],
  ['notice.holdLimit until a time', () => notice.holdLimit(F, { at: '15:05', work: false }), 'the hold reached its time limit. The work is stopped at your 10% reserve until 15:05. Type a prompt to be asked again, or run /spare10 resume.'],
  ['notice.holdLimit until a time, with work', () => notice.holdLimit(F, { at: '15:05', work: true }), 'the hold reached its time limit. The work is stopped at your 10% reserve until 15:05. Then spare10 continues it, unless a reserve is still reached.'],
  ['stopReply tripped', () => stopReply('tripped', F, 90), 'stopped at the reserve. Type a prompt to be asked again, or run /spare10 resume.'],
  ['stopReply tripped until a time', () => stopReply('tripped', F, 90, { at: '15:05' }), 'stopped at the reserve until 15:05. Then spare10 continues any stopped work. Type a prompt to be asked again, or run /spare10 resume.'],
  ['stopReply tripped until a time, no continue', () => stopReply('tripped', F, 90, { at: '15:05', continues: false }), 'stopped at the reserve until 15:05. Type a prompt to be asked again, or run /spare10 resume.'],
  ['stopReply open', () => stopReply('open', [LEAD]), 'nothing to stop. The reset is near, so your 10% reserve is open until 15:00. To keep a reserve until the reset, set its Open reserve option to 0 in /config.'],
  ['notPerson', () => notPerson('stop'), 'only you can run /spare10 stop. Nothing changed.'],
  ['unknownVerb', () => unknownVerb('pause'), 'unknown command "pause". Use /spare10, /spare10 resume or /spare10 stop.'],
  ['simulateReply bad', () => simulateReply('bad'), '/spare10 simulate takes a percentage from 0 to 100, or off. Add weekly for the weekly window, and in 22m for a test window that resets in 22 minutes.'],
  ['simulateReply set', () => simulateReply('set', F), 'test reading set to 92% used, resets 15:00. It can only raise the real reading. Run /spare10 simulate off to clear it.'],
  ['simulateReply raised', () => simulateReply('raised', F), 'test reading raised to 92% used, resets 15:00. Your earlier answers stay. It can only raise the real reading. Run /spare10 simulate off to clear it.'],
  ['commandFailed', () => commandFailed('boom'), '/spare10 failed: boom'],
  ['report: armed, the claude -p row and both help lines', () => statusReport(status()), [
      'version 0.3.0',
      '',
      '  ● armed          spare10 steps in at 90% used.',
      '  · reserve        10% of the 5-hour window (from /config)',
      '  · at the reserve stop and ask you',
      '  · reading        live · 50% used · 50% left · resets 15:00 (in 3 h 0 min)',
      '  · consent        none',
      '  · guarded        yes (scope all)',
      '  · claude -p      runs started here: stop',
      '',
      '/spare10 resume   continue on the reserve until the window resets',
      '/spare10 stop     stop at the reserve now',
    ].join('\n')],
  ['report: every row from its option, and the floor help line', () => statusReport(full()), [
      'version 0.3.0',
      '',
      '  ● armed          spare10 steps in at 90% used, or at 90% used of the weekly window.',
      '  · reserve        10% of the 5-hour window (from /config)',
      '  · weekly reserve 10% of the weekly window (from /config)',
      '  · reserve opens  in the last 20 min of the 5-hour window (from /config)',
      '  · weekly opens   in the last 8 h of the weekly window (from /config)',
      '  · resume floor   5%: after a Resume, spare10 asks again at 95% used (from /config)',
      '  · weekly floor   5%: after a Resume, spare10 asks again at 95% used of the weekly window (from /config)',
      '  · at the reserve stop and ask you',
      '  · at the reset   continue by itself (from /config)',
      '  · reading        live · 50% used · 50% left · resets 15:00 (in 3 h 0 min)',
      '  · weekly reading live · 61% used · 39% left · resets Sun 15:00 (in 3 d 3 h)',
      '  · consent        none',
      '  · weekly consent none',
      '  · guarded        yes (scope all)',
      '  · claude -p      runs started here: stop',
      '',
      '/spare10 resume   continue on the reserve until the floor, or past the floor until the reset',
      '/spare10 stop     stop at the reserve now',
    ].join('\n')],
  ['report: the unattended row', () => statusReport(full({ attended: false, phase: 'reserve', headless: 'stop' })), [
      'version 0.3.0',
      '',
      '  ⚠ tripped        unattended run, policy stop.',
      '  · reserve        10% of the 5-hour window (from /config)',
      '  · weekly reserve 10% of the weekly window (from /config)',
      '  · reserve opens  in the last 20 min of the 5-hour window (from /config)',
      '  · weekly opens   in the last 8 h of the weekly window (from /config)',
      '  · resume floor   5%: this run is unattended and never asks, so the floor does nothing (from /config)',
      '  · weekly floor   5%: this run is unattended and never asks, so the floor does nothing (from /config)',
      '  · at the reserve unattended policy stop',
      '  · reading        live · 50% used · 50% left · resets 15:00 (in 3 h 0 min)',
      '  · weekly reading live · 61% used · 39% left · resets Sun 15:00 (in 3 d 3 h)',
      '  · consent        none',
      '  · weekly consent none',
      '  · guarded        no: this session is unattended.',
      '  · unattended     stop (from /config)',
      '',
      '/spare10 resume   continue on the reserve until the window resets',
      '/spare10 stop     stop at the reserve now',
    ].join('\n')],
  ['report: spans the env could not read', () => statusReport(full({ spans: { lastMinutes: 0, lastMinutesFrom: 'unread', weeklyLastHours: 0, weeklyLastHoursFrom: 'unread' } })), [
      'version 0.3.0',
      '',
      '  ● armed          spare10 steps in at 90% used, or at 90% used of the weekly window.',
      '  · reserve        10% of the 5-hour window (from /config)',
      '  · weekly reserve 10% of the weekly window (from /config)',
      '  · reserve opens  only at the reset (spare10 could not read the env)',
      '  · weekly opens   only at the reset (spare10 could not read the env)',
      '  · resume floor   5%: after a Resume, spare10 asks again at 95% used (from /config)',
      '  · weekly floor   5%: after a Resume, spare10 asks again at 95% used of the weekly window (from /config)',
      '  · at the reserve stop and ask you',
      '  · at the reset   continue by itself (from /config)',
      '  · reading        live · 50% used · 50% left · resets 15:00 (in 3 h 0 min)',
      '  · weekly reading live · 61% used · 39% left · resets Sun 15:00 (in 3 d 3 h)',
      '  · consent        none',
      '  · weekly consent none',
      '  · guarded        yes (scope all)',
      '  · claude -p      runs started here: stop',
      '',
      '/spare10 resume   continue on the reserve until the floor, or past the floor until the reset',
      '/spare10 stop     stop at the reserve now',
    ].join('\n')],
  ['report: weekly off', () => statusReport(status({ weekly: 'off' })), [
      'version 0.3.0',
      '',
      '  ● armed          spare10 steps in at 90% used.',
      '  · reserve        10% of the 5-hour window (from /config)',
      '  · weekly reserve off. spare10 does not watch the weekly window (from /config)',
      '  · at the reserve stop and ask you',
      '  · reading        live · 50% used · 50% left · resets 15:00 (in 3 h 0 min)',
      '  · consent        none',
      '  · guarded        yes (scope all)',
      '  · claude -p      runs started here: stop',
      '',
      '/spare10 resume   continue on the reserve until the window resets',
      '/spare10 stop     stop at the reserve now',
    ].join('\n')],
  ['report: the asking phase', () => statusReport(status({ phase: 'asking' })), [
      'version 0.3.0',
      '',
      '  ? asking         a question is open. Held work waits until you answer. If no dialog shows, run /spare10 resume or /spare10 stop.',
      '  · reserve        10% of the 5-hour window (from /config)',
      '  · at the reserve stop and ask you',
      '  · reading        live · 50% used · 50% left · resets 15:00 (in 3 h 0 min)',
      '  · consent        none',
      '  · guarded        yes (scope all)',
      '  · claude -p      runs started here: stop',
      '',
      '/spare10 resume   continue on the reserve until the window resets',
      '/spare10 stop     stop at the reserve now',
    ].join('\n')],
  ['report: the asking phase with a continue time', () => statusReport(full({ phase: 'asking', at: { ms: R, kinds: ['five_hour'] } })), [
      'version 0.3.0',
      '',
      '  ? asking         a question is open. Held work waits until you answer, or until 15:00. If no dialog shows, run /spare10 resume or /spare10 stop.',
      '  · reserve        10% of the 5-hour window (from /config)',
      '  · weekly reserve 10% of the weekly window (from /config)',
      '  · reserve opens  in the last 20 min of the 5-hour window (from /config)',
      '  · weekly opens   in the last 8 h of the weekly window (from /config)',
      '  · resume floor   5%: after a Resume, spare10 asks again at 95% used (from /config)',
      '  · weekly floor   5%: after a Resume, spare10 asks again at 95% used of the weekly window (from /config)',
      '  · at the reserve stop and ask you',
      '  · at the reset   continue by itself (from /config)',
      '  · reading        live · 50% used · 50% left · resets 15:00 (in 3 h 0 min)',
      '  · weekly reading live · 61% used · 39% left · resets Sun 15:00 (in 3 d 3 h)',
      '  · consent        none',
      '  · weekly consent none',
      '  · guarded        yes (scope all)',
      '  · claude -p      runs started here: stop',
      '',
      '/spare10 resume   continue on the reserve until the floor, or past the floor until the reset',
      '/spare10 stop     stop at the reserve now',
    ].join('\n')],
  ['report: the stopped phase', () => statusReport(status({ phase: 'stopped' })), [
      'version 0.3.0',
      '',
      '  ■ stopped        you chose Stop here. Type a prompt to be asked again, or run /spare10 resume.',
      '  · reserve        10% of the 5-hour window (from /config)',
      '  · at the reserve stop and ask you',
      '  · reading        live · 50% used · 50% left · resets 15:00 (in 3 h 0 min)',
      '  · consent        none',
      '  · guarded        yes (scope all)',
      '  · claude -p      runs started here: stop',
      '',
      '/spare10 resume   continue on the reserve until the window resets',
      '/spare10 stop     stop at the reserve now',
    ].join('\n')],
  ['report: the stopped phase with a continue time', () => statusReport(full({ phase: 'stopped', at: { ms: R, kinds: ['five_hour'] }, autoStop: true, work: true })), [
      'version 0.3.0',
      '',
      '  ■ stopped        you chose Stop here. spare10 continues the work after 15:00. Type a prompt to be asked again, or run /spare10 resume.',
      '  · reserve        10% of the 5-hour window (from /config)',
      '  · weekly reserve 10% of the weekly window (from /config)',
      '  · reserve opens  in the last 20 min of the 5-hour window (from /config)',
      '  · weekly opens   in the last 8 h of the weekly window (from /config)',
      '  · resume floor   5%: after a Resume, spare10 asks again at 95% used (from /config)',
      '  · weekly floor   5%: after a Resume, spare10 asks again at 95% used of the weekly window (from /config)',
      '  · at the reserve stop and ask you',
      '  · at the reset   continue by itself (from /config)',
      '  · reading        live · 50% used · 50% left · resets 15:00 (in 3 h 0 min)',
      '  · weekly reading live · 61% used · 39% left · resets Sun 15:00 (in 3 d 3 h)',
      '  · consent        none',
      '  · weekly consent none',
      '  · guarded        yes (scope all)',
      '  · claude -p      runs started here: stop',
      '',
      '/spare10 resume   continue on the reserve until the floor, or past the floor until the reset',
      '/spare10 stop     stop at the reserve now',
    ].join('\n')],
  ['report: the blind phase and reading', () => statusReport(status({ phase: 'blind', basis: { kind: 'none', why: 'blind' }, facts: undefined })), [
      'version 0.3.0',
      '',
      '  ⚠ blind          Claude Code reports no 5-hour quota. spare10 lets all work through.',
      '  · reserve        10% of the 5-hour window (from /config)',
      '  · at the reserve stop and ask you',
      '  · reading        none: Claude Code reports no quota (blind)',
      '  · consent        none',
      '  · guarded        yes (scope all)',
      '  · claude -p      runs started here: stop',
      '',
      '/spare10 resume   continue on the reserve until the window resets',
      '/spare10 stop     stop at the reserve now',
    ].join('\n')],
  ['report: scope opt-in', () => statusReport(status({ phase: 'off', enabled: false, scope: 'opt-in' })), [
      'version 0.3.0',
      '',
      '  ○ off            spare10 only watches in this run.',
      '  · reserve        10% of the 5-hour window (from /config)',
      '  · at the reserve stop and ask you',
      '  · reading        live · 50% used · 50% left · resets 15:00 (in 3 h 0 min)',
      '  · consent        none',
      '  · guarded        no: scope opt-in. Start with SPARE10=on to guard a run.',
      '  · claude -p      runs started here: stop',
      '',
      '/spare10 resume   continue on the reserve until the window resets',
      '/spare10 stop     stop at the reserve now',
    ].join('\n')],
]

for (const [name, got, want] of GOLDEN) {
  test(`${name} renders the text of 8a342db`, () => {
    expect(got()).toBe(want)
  })
}
