// Builds the Codex bundle (Codex design 6.2): codex/src and the pure hooks/core, with the Codex host words.
// codex/src/main.ts gives codex/dist/spare10.mjs (the broker). codex/src/cli.ts gives codex/dist/cli.mjs (the CLI).
// Both are committed, because the Codex plugin cache is a copy with no node_modules.
// Usage: node scripts/build-codex.mjs          writes codex/dist
//        node scripts/build-codex.mjs --check  compares a fresh build with codex/dist, byte for byte
import { build } from 'esbuild'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// Every path comment in the bundle is relative to the repo root, so the output is the same on each machine.
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
process.chdir(root)

const LINE = '// Generated by scripts/build-codex.mjs from codex/src and hooks/core. Do not edit.'
const coreHost = resolve(root, 'hooks/core/host.ts')
const codexHost = resolve(root, 'codex/src/host.ts')

// Every import of hooks/core/host.ts gets the Codex host words, as codex/test/host-hooks.mjs does for the specs.
const hostSwap = {
  name: 'spare10-host',
  setup(b) {
    b.onResolve({ filter: /[\\/]host\.ts$/ }, (a) =>
      a.importer !== '' && resolve(dirname(a.importer), a.path) === coreHost ? { path: codexHost } : undefined)
  },
}

const common = {
  absWorkingDir: root,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  charset: 'utf8',
  legalComments: 'none',
  minify: false,
  sourcemap: false,
  treeShaking: true,
  logLevel: 'warning',
  plugins: [hostSwap],
}

const outputs = [
  { entry: 'codex/src/main.ts', out: 'codex/dist/spare10.mjs', banner: LINE },
  { entry: 'codex/src/cli.ts', out: 'codex/dist/cli.mjs', banner: `#!/usr/bin/env node\n${LINE}` },
]

const check = process.argv.includes('--check')
let stale = false
for (const o of outputs) {
  const r = await build({ ...common, entryPoints: [o.entry], outfile: o.out, banner: { js: o.banner }, write: false })
  const file = r.outputFiles.find((f) => relative(root, f.path) === o.out)
  if (file === undefined) throw new Error(`build-codex: esbuild gave no ${o.out}`)
  if (check) {
    let old
    try {
      old = readFileSync(o.out)
    } catch {
      old = undefined
    }
    if (old === undefined || !Buffer.from(file.contents).equals(old)) stale = true
  } else {
    mkdirSync(dirname(o.out), { recursive: true })
    writeFileSync(o.out, file.contents)
  }
}
if (stale) {
  process.stderr.write('codex/dist is stale. Run npm run build:codex.\n')
  process.exit(1)
}
