import { test } from 'node:test'
import type { TestContext } from 'node:test'
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { chmodSync, existsSync, mkdirSync, readdirSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { VERSION } from '../../hooks/core/text.ts'
import { realClock } from '../src/clock.ts'
import { tempDir } from './helpers/tmp.ts'

// The committed bundle (Codex design 6.2): codex/dist/spare10.mjs (the broker) and codex/dist/cli.mjs (the CLI).
// scripts/check.sh proves that they are fresh (build-codex.mjs --check). These cases prove what the plugin
// cache runs: the banner, the Codex host words, no dependency and no Node.js API newer than Node.js 20, a
// broker that answers `initialize` through codex/bin/broker.sh, and the clear error when no Node.js 20 exists.
// broker.sh runs outside the Codex sandbox, so a case proves that it runs nothing from PATH while a fixed Node.js
// exists. Other cases prove that it skips an old Node.js, that its version probe cannot touch the MCP stream, and
// that it runs no node from a relative folder. The Node.js 20.0 job of .github/workflows/codex.yml loads both
// bundles, for what DENY cannot see.

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const LINE = '// Generated by scripts/build-codex.mjs from codex/src and hooks/core. Do not edit.'
const BUNDLES: ReadonlyArray<readonly [string, string]> = [
  ['codex/dist/spare10.mjs', `${LINE}\n`],
  ['codex/dist/cli.mjs', `#!/usr/bin/env node\n${LINE}\n`],
]
const read = (file: string): string => readFileSync(join(ROOT, file), 'utf8')

/** Node.js APIs newer than Node.js 20.0: the bundle targets Node.js 20 (6.2), and broker.sh takes any 20.x. */
const DENY: ReadonlyArray<readonly [string, RegExp]> = [
  ['fs.glob', /\bglob(Sync)?\s*\(/],
  ['process.getBuiltinModule', /getBuiltinModule/],
  ['Promise.withResolvers', /withResolvers/],
  ['Array.fromAsync', /fromAsync/],
  ['Object.groupBy, Map.groupBy', /\.groupBy\s*\(/],
  ['import.meta.dirname, import.meta.filename', /import\.meta\.(dirname|filename)/],
  ['Set methods', /\.(union|intersection|symmetricDifference|isSubsetOf|isSupersetOf|isDisjointFrom)\s*\(/],
  ['util.styleText', /styleText/],
  ['process.loadEnvFile', /loadEnvFile/],
  ['navigator', /\bnavigator\./],
  ['WebSocket', /new WebSocket\b/],
  ['Iterator helpers', /\bIterator\.from\b/],
  ['URL.parse', /\bURL\.parse\s*\(/],
  ['RegExp.escape', /RegExp\.escape/],
  ['Error.isError', /Error\.isError/],
  ['Float16Array', /Float16Array/],
  ['path.matchesGlob', /matchesGlob/],
  ['zlib.crc32', /\bcrc32\b/],
  ['crypto.hash', /import \{[^}]*\bhash\b[^}]*\} from "node:crypto"|\bcrypto\d*\.hash\s*\(/],
  ['util.parseEnv', /parseEnv/],
  ['stream.duplexPair', /duplexPair/],
  ['module.enableCompileCache, module.findPackageJSON', /enableCompileCache|findPackageJSON/],
  ['AbortSignal.any', /AbortSignal\.any\s*\(/],
  ['Promise.try', /Promise\.try\s*\(/],
  ['util.getCallSites', /getCallSites?\b/],
  ['node:sqlite, node:sea', /from "node:(sqlite|sea)"/],
]

/** A line of bundle code for each DENY entry, as esbuild writes it. */
const DENIED: Readonly<Record<string, string>> = {
  'fs.glob': 'const files = globSync("*.json");',
  'process.getBuiltinModule': 'const fs = process.getBuiltinModule("node:fs");',
  'Promise.withResolvers': 'const { promise, resolve } = Promise.withResolvers();',
  'Array.fromAsync': 'const all = await Array.fromAsync(lines);',
  'Object.groupBy, Map.groupBy': 'const byKind = Object.groupBy(rows, (r) => r.kind);',
  'import.meta.dirname, import.meta.filename': 'const here = import.meta.dirname;',
  'Set methods': 'const both = a.union(b);',
  'util.styleText': 'import { styleText } from "node:util";',
  'process.loadEnvFile': 'process.loadEnvFile(".env");',
  navigator: 'const n = navigator.hardwareConcurrency;',
  WebSocket: 'const ws = new WebSocket(url);',
  'Iterator helpers': 'const it = Iterator.from(gen);',
  'URL.parse': 'const u = URL.parse(text);',
  'RegExp.escape': 'const re = new RegExp(RegExp.escape(name));',
  'Error.isError': 'if (Error.isError(e)) throw e;',
  Float16Array: 'const h = new Float16Array(2);',
  'path.matchesGlob': 'import { join as join2, matchesGlob } from "node:path";',
  'zlib.crc32': 'import { crc32 } from "node:zlib";',
  'crypto.hash': 'import {\n  createHash,\n  hash as hash2\n} from "node:crypto";',
  'util.parseEnv': 'import { parseEnv } from "node:util";',
  'stream.duplexPair': 'import { duplexPair } from "node:stream";',
  'module.enableCompileCache, module.findPackageJSON': 'import { findPackageJSON } from "node:module";',
  'AbortSignal.any': 'const signal = AbortSignal.any([a, b]);',
  'Promise.try': 'const p = Promise.try(() => read());',
  'util.getCallSites': 'import { getCallSites } from "node:util";',
  'node:sqlite, node:sea': 'import { DatabaseSync } from "node:sqlite";',
}

type Run = { code: number | null; stdout: string; stderr: string; ms: number }

/** Runs a command in the repo root with `input` as its stdin, and gives up after `limitMs`. */
function run(t: TestContext, cmd: string, args: readonly string[], env: Record<string, string>, o: { input?: string; waitFor?: RegExp; limitMs?: number } = {}): Promise<Run> {
  return new Promise((done, fail) => {
    const start = realClock.now()
    const child = spawn(cmd, args, { cwd: ROOT, env, stdio: ['pipe', 'pipe', 'pipe'] })
    let stdout = ''
    let stderr = ''
    let at = 0
    const limit = realClock.after(o.limitMs ?? 10_000, () => {
      child.kill('SIGKILL')
      fail(new Error(`${cmd} ${args.join(' ')} gave no result in ${o.limitMs ?? 10_000} ms. stdout: ${stdout} stderr: ${stderr}`))
    })
    t.after(() => {
      limit.cancel()
      child.kill('SIGKILL')
    })
    child.stdout.setEncoding('utf8')
    child.stderr.setEncoding('utf8')
    child.stdout.on('data', (s: string) => {
      stdout += s
      if (at === 0 && o.waitFor !== undefined && o.waitFor.test(stdout)) {
        at = realClock.now() - start
        child.stdin.end()
      }
    })
    child.stderr.on('data', (s: string) => (stderr += s))
    child.on('error', fail)
    child.on('close', (code) => {
      limit.cancel()
      done({ code, stdout, stderr, ms: at || realClock.now() - start })
    })
    if (o.input !== undefined) child.stdin.write(o.input)
    if (o.waitFor === undefined) child.stdin.end()
  })
}

/** A temp HOME, CODEX_HOME and data dir, and a PATH that holds only this Node.js (no codex). */
function world(t: TestContext): { dir: string; env: Record<string, string> } {
  const dir = tempDir(t, 's10b')
  const bin = join(dir, 'bin')
  mkdirSync(bin)
  mkdirSync(join(dir, 'home'))
  symlinkSync(process.execPath, join(bin, 'node'))
  const env = {
    HOME: join(dir, 'home'),
    PATH: `${bin}:/usr/bin:/bin`,
    CODEX_HOME: join(dir, 'codex-home'),
    SPARE10_CODEX_DATA: join(dir, 'data'),
    SPARE10_CODEX_TEST: '1',
  }
  return { dir, env }
}

const rpc = (...lines: object[]): string => lines.map((l) => `${JSON.stringify(l)}\n`).join('')

for (const [file, banner] of BUNDLES) {
  test(`bundle: ${file} starts with the banner, has the Codex host words and needs nothing but Node.js 20`, () => {
    const js = read(file)
    assert.ok(js.startsWith(banner), `${file} starts with the banner`)
    assert.match(js, /name: "Codex"/)
    assert.match(js, /anytime: "!spare10"/)
    assert.doesNotMatch(js, /command: "\/spare10"/)
    assert.doesNotMatch(js, /name: "Claude Code"/)
    assert.ok(js.includes(`"${VERSION}"`), `${file} holds VERSION ${VERSION}`)
    const imports = [...js.matchAll(/^import .* from "([^"]+)";$/gm)].map((m) => m[1] as string)
    assert.ok(imports.length > 0)
    for (const spec of imports) assert.match(spec, /^node:/, `${file} imports only Node.js built-ins, not ${spec}`)
    assert.doesNotMatch(js, /\brequire\s*\(/)
    for (const [name, re] of DENY) assert.doesNotMatch(js, re, `${file} uses ${name}, which Node.js 20 lacks`)
  })
}

test('bundle: each DENY entry finds its API in a line of bundle code, and not in the APIs of Node.js 20.0', () => {
  assert.deepEqual(DENY.map(([name]) => name), Object.keys(DENIED))
  for (const [name, re] of DENY) assert.match(DENIED[name] ?? '', re, name)
  // Names that Node.js 20.0 has, and that the bundle uses.
  const fine = 'import { createHash, randomBytes as randomBytes3 } from "node:crypto";\nconst h = createHash("sha256");\nconst t = AbortSignal.timeout(5);'
  for (const [name, re] of DENY) assert.doesNotMatch(fine, re, name)
})

test('bundle: codex/bin/broker.sh starts the broker, which answers initialize within 1 s and lists no tools', async (t) => {
  const w = world(t)
  // broker.sh tries the fixed places before PATH. They move away here, so the case times this Node.js on PATH, and
  // not a Node.js of the machine that no process ran yet.
  const script = movedBroker(w.dir, {})
  const r = await run(t, '/bin/sh', [script], w.env, {
    input: rpc(
      { jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 't', version: '0' } } },
      { jsonrpc: '2.0', id: 2, method: 'tools/list', params: {} },
    ),
    waitFor: /"id":2/,
  })
  t.diagnostic(`initialize and tools/list answered in ${r.ms} ms`)
  assert.equal(r.code, 0, r.stderr)
  const replies = r.stdout.trim().split('\n').map((l) => JSON.parse(l) as { id?: number; result?: unknown })
  assert.deepEqual(replies.find((m) => m.id === 1)?.result, {
    protocolVersion: '2025-06-18',
    capabilities: { tools: {} },
    serverInfo: { name: 'spare10', version: VERSION },
  })
  assert.deepEqual(replies.find((m) => m.id === 2)?.result, { tools: [] })
  assert.ok(r.ms < 1_000, `the broker answered in ${r.ms} ms`)
})

test('bundle: the broker answers a gate through codex/bin/broker.sh', async (t) => {
  const w = world(t)
  const gate = { site: 'prompt', session: 's1', turn: 't1', transcript: null, mode: 'default', model: 'm', cwd: w.dir, prompt: 'spare10 help' }
  const r = await run(t, '/bin/sh', ['./codex/bin/broker.sh'], w.env, {
    input: rpc(
      { jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 't', version: '0' } } },
      { jsonrpc: '2.0', method: 'notifications/initialized' },
      { jsonrpc: '2.0', id: 2, method: 'tools/call', params: { name: 'gate', arguments: gate, _meta: { threadId: 's1' } } },
    ),
    waitFor: /"id":2/,
  })
  assert.equal(r.code, 0, r.stderr)
  const reply = r.stdout.trim().split('\n').map((l) => JSON.parse(l) as { id?: number; result?: { content: Array<{ text: string }>; isError: boolean } }).find((m) => m.id === 2)
  assert.equal(reply?.result?.isError, false)
  const answer = JSON.parse(reply?.result?.content[0]?.text ?? '') as { decision?: string; reason?: string }
  assert.equal(answer.decision, 'block')
  assert.match(answer.reason ?? '', /^spare10: commands, typed as the whole prompt:\n/)
})

test('bundle: codex/dist/cli.mjs runs as a program and prints the usage for a bad verb', async (t) => {
  const w = world(t)
  const r = await run(t, process.execPath, ['codex/dist/cli.mjs', 'bogus', '--data', w.env.SPARE10_CODEX_DATA as string], w.env)
  assert.equal(r.code, 2, r.stderr)
  assert.match(r.stdout, /^usage: spare10 /)
})

/**
 * codex/bin/broker.sh with its fixed places moved under `dir`, so the case does not depend on the Node.js
 * installs of this machine. `nodes` maps a place (a PATH folder, a fixed place or an nvm version) to a
 * script, or to 'real' for this Node.js.
 */
function movedBroker(dir: string, nodes: Record<string, 'old' | 'real'>): string {
  const fixed = ['/opt/homebrew/bin/node', '/usr/local/bin/node', '/usr/bin/node']
  let sh = read('codex/bin/broker.sh')
  for (const f of fixed) {
    assert.ok(sh.includes(` ${f}`), `broker.sh names ${f}`)
    sh = sh.replace(` ${f}`, ` ${join(dir, 'fixed', f)}`)
  }
  for (const [place, kind] of Object.entries(nodes)) {
    const file = place.startsWith('/') ? join(dir, 'fixed', place) : join(dir, place)
    mkdirSync(dirname(file), { recursive: true })
    if (kind === 'real') symlinkSync(process.execPath, file)
    else {
      // An old Node.js: it fails the version check of broker.sh.
      writeFileSync(file, '#!/bin/sh\nexit 1\n')
      chmodSync(file, 0o755)
    }
  }
  const out = join(dir, 'broker.sh')
  writeFileSync(out, sh)
  return out
}

test('bundle: with no Node.js 20 or later, broker.sh prints the stderr line and exits 1', async (t) => {
  const w = world(t)
  const home = join(w.dir, 'home')
  const script = movedBroker(w.dir, { 'path/node': 'old', '/opt/homebrew/bin/node': 'old', 'home/.nvm/versions/node/v18.20.4/bin/node': 'old' })
  // PATH holds no tools: broker.sh takes them from /usr/bin and /bin.
  const r = await run(t, '/bin/sh', [script], { ...w.env, HOME: home, PATH: join(w.dir, 'path') })
  assert.equal(r.code, 1)
  assert.equal(r.stdout, '')
  assert.equal(r.stderr, 'spare10: no Node.js 20 or later found. Install Node.js, or switch off the spare10 plugin in ~/.codex/config.toml.\n')
})

test('bundle: broker.sh skips an old fixed Node.js and an old Volta Node.js, and finds Node.js 20 or later in an nvm folder', async (t) => {
  const w = world(t)
  const home = join(w.dir, 'home')
  // The old /usr/bin/node of a Linux distro comes first, so broker.sh must probe it and go on.
  const script = movedBroker(w.dir, {
    '/usr/bin/node': 'old',
    'home/.volta/bin/node': 'old',
    'home/.nvm/versions/node/v18.20.4/bin/node': 'old',
    'home/.nvm/versions/node/v22.19.0/bin/node': 'real',
    'path/node': 'old',
  })
  const r = await run(t, '/bin/sh', [script], { ...w.env, HOME: home, PATH: join(w.dir, 'path') }, {
    input: rpc({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 't', version: '0' } } }),
    waitFor: /"id":1/,
  })
  assert.equal(r.code, 0, r.stderr)
  assert.match(r.stdout, /"serverInfo":\{"name":"spare10","version":"[^"]+"\}/)
})

test('bundle: broker.sh takes a fixed Node.js before the one on PATH, and runs no node, tool or ps from PATH', async (t) => {
  // Codex runs broker.sh outside its sandbox, and the agent can write a PATH folder such as the .venv/bin of a project.
  const w = world(t)
  const script = movedBroker(w.dir, { '/opt/homebrew/bin/node': 'real' })
  const venv = join(w.dir, 'venv')
  const marks = join(w.dir, 'marks')
  mkdirSync(venv)
  mkdirSync(marks)
  for (const tool of ['node', 'ls', 'sed', 'sort', 'cut', 'ps']) {
    const real = tool === 'node' ? process.execPath : [`/bin/${tool}`, `/usr/bin/${tool}`].find((f) => existsSync(f))
    assert.ok(real !== undefined, `${tool} exists`)
    // Each stand-in leaves a mark, then runs the real tool, so the broker still works when one runs.
    writeFileSync(join(venv, tool), `#!/bin/sh\n: > '${join(marks, tool)}'\nexec '${real}' "$@"\n`)
    chmodSync(join(venv, tool), 0o755)
  }
  const gate = { site: 'prompt', session: 's1', turn: 't1', transcript: null, mode: 'default', model: 'm', cwd: w.dir, prompt: 'spare10 help' }
  const r = await run(t, '/bin/sh', [script], { ...w.env, PATH: `${venv}:/usr/bin:/bin` }, {
    input: rpc(
      { jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 't', version: '0' } } },
      { jsonrpc: '2.0', method: 'notifications/initialized' },
      { jsonrpc: '2.0', id: 2, method: 'tools/call', params: { name: 'gate', arguments: gate, _meta: { threadId: 's1' } } },
    ),
    waitFor: /"id":2/,
  })
  assert.equal(r.code, 0, r.stderr)
  assert.match(r.stdout, /"serverInfo":\{"name":"spare10","version":"[^"]+"\}/)
  assert.match(r.stdout, /"id":2,"result":\{"content"/)
  assert.deepEqual(readdirSync(marks), [], 'no stand-in on PATH ran')
})

/** A node stand-in at `file`: it runs the sh line `pre`, then this Node.js. */
function standIn(file: string, pre: string): void {
  mkdirSync(dirname(file), { recursive: true })
  writeFileSync(file, `#!/bin/sh\n${pre}\nexec '${process.execPath}' "$@"\n`)
  chmodSync(file, 0o755)
}

test('bundle: broker.sh takes the Node.js on PATH last, and its version probe gets no stdin and no stdout', async (t) => {
  const w = world(t)
  const home = join(w.dir, 'home')
  const script = movedBroker(w.dir, {
    '/opt/homebrew/bin/node': 'old',
    '/usr/local/bin/node': 'old',
    '/usr/bin/node': 'old',
    'home/.volta/bin/node': 'old',
    'home/.nvm/versions/node/v18.20.4/bin/node': 'old',
    'home/.local/share/mise/installs/node/18.20.4/bin/node': 'old',
  })
  // On the probe (-e), the stand-in writes to stdout and reads a line of stdin. With the MCP stream as its
  // stdin and stdout, it takes the initialize line and puts junk in front of the answers.
  const bin = join(w.dir, 'pathbin')
  standIn(join(bin, 'node'), `if [ "$1" = -e ]; then echo 'junk from the probe'; IFS= read -r line; fi`)
  const r = await run(t, '/bin/sh', [script], { ...w.env, HOME: home, PATH: bin }, {
    input: rpc(
      { jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 't', version: '0' } } },
      { jsonrpc: '2.0', id: 2, method: 'tools/list', params: {} },
    ),
    waitFor: /"id":2/,
    limitMs: 5_000,
  })
  assert.equal(r.code, 0, r.stderr)
  const replies = r.stdout.trim().split('\n').map((l) => JSON.parse(l) as { id?: number; result?: { serverInfo?: unknown } })
  assert.deepEqual(replies.find((m) => m.id === 1)?.result?.serverInfo, { name: 'spare10', version: VERSION })
})

test('bundle: broker.sh runs no Node.js from a relative PATH folder or a relative HOME', async (t) => {
  const w = world(t)
  const script = movedBroker(w.dir, {})
  const marks = join(w.dir, 'marks')
  mkdirSync(marks)
  // Both are relative to the plugin root, the cwd of broker.sh. bash makes a node in a relative PATH folder absolute.
  const rel = join(w.dir, 'rel')
  const relHome = join(w.dir, 'relhome')
  standIn(join(rel, 'node'), `: > '${join(marks, 'path')}'`)
  standIn(join(relHome, '.volta', 'bin', 'node'), `: > '${join(marks, 'volta')}'`)
  standIn(join(relHome, '.nvm', 'versions', 'node', 'v22.19.0', 'bin', 'node'), `: > '${join(marks, 'nvm')}'`)
  const r = await run(t, '/bin/sh', [script], { ...w.env, HOME: relative(ROOT, relHome), PATH: relative(ROOT, rel) })
  assert.deepEqual(readdirSync(marks), [], 'no relative node ran')
  assert.equal(r.code, 1)
  assert.equal(r.stdout, '')
  assert.equal(r.stderr, 'spare10: no Node.js 20 or later found. Install Node.js, or switch off the spare10 plugin in ~/.codex/config.toml.\n')
})
