import { test } from 'node:test'
import type { TestContext } from 'node:test'
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { chmodSync, existsSync, mkdirSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { VERSION } from '../../hooks/core/text.ts'
import { realClock } from '../src/clock.ts'
import { tempDir } from './helpers/tmp.ts'

// The committed bundle (Codex design 6.2): codex/dist/spare10.mjs (the broker) and codex/dist/cli.mjs (the CLI).
// scripts/check.sh proves that they are fresh (build-codex.mjs --check). These cases prove what the plugin
// cache runs: the banner, the Codex host words, no dependency and no Node.js API newer than Node.js 20, a
// broker that answers `initialize` through codex/bin/broker.sh, and the clear error when no Node.js 20 exists.

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const LINE = '// Generated by scripts/build-codex.mjs from codex/src and hooks/core. Do not edit.'
const BUNDLES: ReadonlyArray<readonly [string, string]> = [
  ['codex/dist/spare10.mjs', `${LINE}\n`],
  ['codex/dist/cli.mjs', `#!/usr/bin/env node\n${LINE}\n`],
]
const read = (file: string): string => readFileSync(join(ROOT, file), 'utf8')

/** Node.js APIs newer than Node.js 20.0: the bundle targets Node.js 20 (6.2). */
const DENY: ReadonlyArray<readonly [string, RegExp]> = [
  ['fs.glob', /\bglob(Sync)?\s*\(/],
  ['process.getBuiltinModule', /getBuiltinModule/],
  ['Promise.withResolvers', /withResolvers/],
  ['Array.fromAsync', /fromAsync/],
  ['Object.groupBy, Map.groupBy', /\.groupBy\s*\(/],
  ['import.meta.dirname, import.meta.filename', /import\.meta\.(dirname|filename)/],
  ['Set methods', /\.(union|intersection|symmetricDifference|isSubsetOf|isSupersetOf|isDisjointFrom)\s*\(/],
  ['util.styleText', /styleText/],
  ['process.loadEnvFile', /loadEnvFile/],
  ['navigator', /\bnavigator\./],
  ['WebSocket', /new WebSocket\b/],
  ['Iterator helpers', /\bIterator\.from\b/],
  ['URL.parse', /\bURL\.parse\s*\(/],
  ['RegExp.escape', /RegExp\.escape/],
  ['Error.isError', /Error\.isError/],
  ['Float16Array', /Float16Array/],
]

type Run = { code: number | null; stdout: string; stderr: string; ms: number }

/** Runs a command in the repo root with `input` as its stdin, and gives up after `limitMs`. */
function run(t: TestContext, cmd: string, args: readonly string[], env: Record<string, string>, o: { input?: string; waitFor?: RegExp; limitMs?: number } = {}): Promise<Run> {
  return new Promise((done, fail) => {
    const start = realClock.now()
    const child = spawn(cmd, args, { cwd: ROOT, env, stdio: ['pipe', 'pipe', 'pipe'] })
    let stdout = ''
    let stderr = ''
    let at = 0
    const limit = realClock.after(o.limitMs ?? 10_000, () => {
      child.kill('SIGKILL')
      fail(new Error(`${cmd} ${args.join(' ')} gave no result in ${o.limitMs ?? 10_000} ms. stdout: ${stdout} stderr: ${stderr}`))
    })
    t.after(() => {
      limit.cancel()
      child.kill('SIGKILL')
    })
    child.stdout.setEncoding('utf8')
    child.stderr.setEncoding('utf8')
    child.stdout.on('data', (s: string) => {
      stdout += s
      if (at === 0 && o.waitFor !== undefined && o.waitFor.test(stdout)) {
        at = realClock.now() - start
        child.stdin.end()
      }
    })
    child.stderr.on('data', (s: string) => (stderr += s))
    child.on('error', fail)
    child.on('close', (code) => {
      limit.cancel()
      done({ code, stdout, stderr, ms: at || realClock.now() - start })
    })
    if (o.input !== undefined) child.stdin.write(o.input)
    if (o.waitFor === undefined) child.stdin.end()
  })
}

/** A temp HOME, CODEX_HOME and data dir, and a PATH that holds only this Node.js (no codex). */
function world(t: TestContext): { dir: string; env: Record<string, string> } {
  const dir = tempDir(t, 's10b')
  const bin = join(dir, 'bin')
  mkdirSync(bin)
  mkdirSync(join(dir, 'home'))
  symlinkSync(process.execPath, join(bin, 'node'))
  const env = {
    HOME: join(dir, 'home'),
    PATH: `${bin}:/usr/bin:/bin`,
    CODEX_HOME: join(dir, 'codex-home'),
    SPARE10_CODEX_DATA: join(dir, 'data'),
    SPARE10_CODEX_TEST: '1',
  }
  return { dir, env }
}

const rpc = (...lines: object[]): string => lines.map((l) => `${JSON.stringify(l)}\n`).join('')

for (const [file, banner] of BUNDLES) {
  test(`bundle: ${file} starts with the banner, has the Codex host words and needs nothing but Node.js 20`, () => {
    const js = read(file)
    assert.ok(js.startsWith(banner), `${file} starts with the banner`)
    assert.match(js, /name: "Codex"/)
    assert.match(js, /anytime: "!spare10"/)
    assert.doesNotMatch(js, /command: "\/spare10"/)
    assert.doesNotMatch(js, /name: "Claude Code"/)
    assert.ok(js.includes(`"${VERSION}"`), `${file} holds VERSION ${VERSION}`)
    const imports = [...js.matchAll(/^import .* from "([^"]+)";$/gm)].map((m) => m[1] as string)
    assert.ok(imports.length > 0)
    for (const spec of imports) assert.match(spec, /^node:/, `${file} imports only Node.js built-ins, not ${spec}`)
    assert.doesNotMatch(js, /\brequire\s*\(/)
    for (const [name, re] of DENY) assert.doesNotMatch(js, re, `${file} uses ${name}, which Node.js 20 lacks`)
  })
}

test('bundle: codex/bin/broker.sh starts the broker, which answers initialize within 1 s and lists no tools', async (t) => {
  const w = world(t)
  const r = await run(t, '/bin/sh', ['./codex/bin/broker.sh'], w.env, {
    input: rpc(
      { jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 't', version: '0' } } },
      { jsonrpc: '2.0', id: 2, method: 'tools/list', params: {} },
    ),
    waitFor: /"id":2/,
  })
  t.diagnostic(`initialize and tools/list answered in ${r.ms} ms`)
  assert.equal(r.code, 0, r.stderr)
  const replies = r.stdout.trim().split('\n').map((l) => JSON.parse(l) as { id?: number; result?: unknown })
  assert.deepEqual(replies.find((m) => m.id === 1)?.result, {
    protocolVersion: '2025-06-18',
    capabilities: { tools: {} },
    serverInfo: { name: 'spare10', version: VERSION },
  })
  assert.deepEqual(replies.find((m) => m.id === 2)?.result, { tools: [] })
  assert.ok(r.ms < 1_000, `the broker answered in ${r.ms} ms`)
})

test('bundle: the broker answers a gate through codex/bin/broker.sh', async (t) => {
  const w = world(t)
  const gate = { site: 'prompt', session: 's1', turn: 't1', transcript: null, mode: 'default', model: 'm', cwd: w.dir, prompt: 'spare10 help' }
  const r = await run(t, '/bin/sh', ['./codex/bin/broker.sh'], w.env, {
    input: rpc(
      { jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 't', version: '0' } } },
      { jsonrpc: '2.0', method: 'notifications/initialized' },
      { jsonrpc: '2.0', id: 2, method: 'tools/call', params: { name: 'gate', arguments: gate, _meta: { threadId: 's1' } } },
    ),
    waitFor: /"id":2/,
  })
  assert.equal(r.code, 0, r.stderr)
  const reply = r.stdout.trim().split('\n').map((l) => JSON.parse(l) as { id?: number; result?: { content: Array<{ text: string }>; isError: boolean } }).find((m) => m.id === 2)
  assert.equal(reply?.result?.isError, false)
  const answer = JSON.parse(reply?.result?.content[0]?.text ?? '') as { decision?: string; reason?: string }
  assert.equal(answer.decision, 'block')
  assert.match(answer.reason ?? '', /^spare10: commands, typed as the whole prompt:\n/)
})

test('bundle: codex/dist/cli.mjs runs as a program and prints the usage for a bad verb', async (t) => {
  const w = world(t)
  const r = await run(t, process.execPath, ['codex/dist/cli.mjs', 'bogus', '--data', w.env.SPARE10_CODEX_DATA as string], w.env)
  assert.equal(r.code, 2, r.stderr)
  assert.match(r.stdout, /^usage: spare10 /)
})

/**
 * codex/bin/broker.sh with its fixed places moved under `dir`, so the case does not depend on the Node.js
 * installs of this machine. `nodes` maps a place (a PATH folder, a fixed place or an nvm version) to a
 * script, or to 'real' for this Node.js.
 */
function movedBroker(dir: string, nodes: Record<string, 'old' | 'real'>): string {
  const fixed = ['/opt/homebrew/bin/node', '/usr/local/bin/node', '/usr/bin/node']
  let sh = read('codex/bin/broker.sh')
  for (const f of fixed) {
    assert.ok(sh.includes(` ${f}`), `broker.sh names ${f}`)
    sh = sh.replace(` ${f}`, ` ${join(dir, 'fixed', f)}`)
  }
  for (const [place, kind] of Object.entries(nodes)) {
    const file = place.startsWith('/') ? join(dir, 'fixed', place) : join(dir, place)
    mkdirSync(dirname(file), { recursive: true })
    if (kind === 'real') symlinkSync(process.execPath, file)
    else {
      // An old Node.js: it fails the version check of broker.sh.
      writeFileSync(file, '#!/bin/sh\nexit 1\n')
      chmodSync(file, 0o755)
    }
  }
  const out = join(dir, 'broker.sh')
  writeFileSync(out, sh)
  // The tools of broker.sh, with no Node.js next to them: /usr/bin can hold one on Linux.
  mkdirSync(join(dir, 'tools'))
  for (const tool of ['ls', 'sed', 'sort', 'cut']) {
    const found = [`/bin/${tool}`, `/usr/bin/${tool}`].find((f) => existsSync(f))
    assert.ok(found !== undefined, `${tool} exists`)
    symlinkSync(found, join(dir, 'tools', tool))
  }
  return out
}

test('bundle: with no Node.js 20 or later, broker.sh prints the stderr line and exits 1', async (t) => {
  const w = world(t)
  const home = join(w.dir, 'home')
  const script = movedBroker(w.dir, { 'path/node': 'old', '/opt/homebrew/bin/node': 'old', 'home/.nvm/versions/node/v18.20.4/bin/node': 'old' })
  const r = await run(t, '/bin/sh', [script], { ...w.env, HOME: home, PATH: `${join(w.dir, 'path')}:${join(w.dir, 'tools')}` })
  assert.equal(r.code, 1)
  assert.equal(r.stdout, '')
  assert.equal(r.stderr, 'spare10: no Node.js 20 or later found. Install Node.js, or switch off the spare10 plugin in ~/.codex/config.toml.\n')
})

test('bundle: broker.sh skips an old Node.js on PATH and finds Node.js 20 or later in an nvm folder', async (t) => {
  const w = world(t)
  const home = join(w.dir, 'home')
  const script = movedBroker(w.dir, { 'path/node': 'old', 'home/.nvm/versions/node/v18.20.4/bin/node': 'old', 'home/.nvm/versions/node/v22.19.0/bin/node': 'real' })
  const r = await run(t, '/bin/sh', [script], { ...w.env, HOME: home, PATH: `${join(w.dir, 'path')}:${join(w.dir, 'tools')}` }, {
    input: rpc({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 't', version: '0' } } }),
    waitFor: /"id":1/,
  })
  assert.equal(r.code, 0, r.stderr)
  assert.match(r.stdout, /"serverInfo":\{"name":"spare10","version":"[^"]+"\}/)
})
